import mongoose from 'mongoose'
import Product from '../models/Product.js'
import {
  isAiChatAvailable,
  buildInspectionContext,
  askComplianceQuestion,
} from '../services/aiChatService.js'

/**
 * POST /api/chat/ask
 * Ask the AI assistant a question about an existing inspection.
 *
 * The compliance system continues working if this endpoint fails or
 * the AI provider is unavailable.
 *
 * Request body: { productId, question }
 */
export async function askQuestion(req, res, next) {
  try {
    const { productId, question } = req.body
    const userId = req.user.userId

    if (!productId || !question) {
      return res.status(400).json({
        success: false,
        message: 'productId and question are required',
      })
    }

    if (!mongoose.Types.ObjectId.isValid(productId)) {
      return res.status(400).json({ success: false, message: 'Invalid productId' })
    }

    const q = String(question).trim()
    if (q.length < 3 || q.length > 1000) {
      return res.status(400).json({
        success: false,
        message: 'Question must be between 3 and 1000 characters',
      })
    }

    // If AI is not configured, return graceful unavailable state
    if (!isAiChatAvailable()) {
      return res.status(200).json({
        success: true,
        available: false,
        message:
          'AI assistant is not configured. Please set AI_CHAT_PROVIDER, AI_CHAT_MODEL, and AI_CHAT_API_KEY.',
      })
    }

    // Ownership check — inspector can only ask about their own products
    const product = await Product.findOne({ _id: productId, userId }).lean()
    if (!product) {
      return res.status(404).json({
        success: false,
        message: 'Product not found or access denied',
      })
    }

    // Build safe context from persisted data — no raw private info
    const context = buildInspectionContext(product)

    let answer
    try {
      answer = await askComplianceQuestion(context, q)
    } catch (aiErr) {
      // AI provider error — return safe response, do NOT crash the app
      console.error('[ChatController] AI provider error:', aiErr.message)
      return res.status(200).json({
        success: true,
        available: false,
        message: 'AI assistant is temporarily unavailable. Please try again later.',
      })
    }

    if (answer === null) {
      return res.status(200).json({
        success: true,
        available: false,
        message: 'AI assistant is not configured.',
      })
    }

    return res.status(200).json({
      success: true,
      available: true,
      question: q,
      answer,
      disclaimer:
        'This response is generated by an AI assistant to help explain the inspection data. It does not constitute a legal determination.',
    })
  } catch (err) {
    return next(err)
  }
}
