/**
 * Annotation Verification Service
 * Exposes the strict logic for promoting a weak_candidate to a human_verified ground truth.
 */

export class AnnotationVerificationService {
  /**
   * Promotes a candidate annotation to ground truth if it has been reviewed.
   * 
   * @param {Object} originalCandidate The weak candidate object generated by weakRoiCandidateService
   * @param {Object} reviewData The human review data { status: 'approved'|'corrected'|'rejected', finalBBox: [x,y,w,h] }
   * @param {string} reviewerType Usually 'human'
   * @returns {Object} The promoted annotation or null if rejected.
   */
  static processVerification(originalCandidate, reviewData, reviewerType = 'human') {
    if (!originalCandidate) {
      throw new Error("Missing original candidate data.");
    }
    
    if (originalCandidate.provenance !== 'weak_candidate') {
      throw new Error(`Cannot verify an annotation with provenance: ${originalCandidate.provenance}`);
    }

    const { status, finalBBox } = reviewData;
    
    if (!['approved', 'corrected', 'rejected'].includes(status)) {
      throw new Error(`Invalid review status: ${status}. Must be approved, corrected, or rejected.`);
    }

    if (status === 'rejected') {
      return null; // The human decided this bounding box was a false positive.
    }

    if (status === 'corrected' && (!finalBBox || finalBBox.length !== 4)) {
      throw new Error("Corrected status requires a valid finalBBox array of length 4.");
    }

    return {
      classId: originalCandidate.classId,
      className: originalCandidate.className,
      bbox: status === 'corrected' ? finalBBox : originalCandidate.bbox,
      provenance: 'proprietary_human_verified',
      originalProvenance: originalCandidate.provenance,
      reviewStatus: status,
      reviewTimestamp: new Date().toISOString(),
      reviewerType: reviewerType,
      originalCandidateBBox: originalCandidate.bbox,
      sourceOcrDetectionIds: originalCandidate.sourceOcrDetectionIds || []
    };
  }

  /**
   * Validates that an array of final annotations does not contain unverified candidates.
   * Throws an error if contamination is detected.
   */
  static ensureNoWeakCandidates(annotations) {
    for (const ann of annotations) {
      if (ann.provenance === 'weak_candidate') {
        throw new Error("FATAL: Ground truth dataset contamination. Weak candidate detected in final export.");
      }
    }
    return true;
  }
}
